name: ev_shoe_controller
description: "EV Bluetooth Shoe Controller App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.29.11
  flutter_joystick: ^0.0.4
  lottie: ^2.7.0
  go_router: ^12.1.1
  kdgaugeview: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottiefiles/
    - assets/images/logo.png
    - assets/images/Backgroud.png
    - assets/images/app_logo.jpg
    - assets/images/esp32.png
    - assets/images/Rasberry.png